services:
  sqlpad:
    image: sqlpad/sqlpad
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: admin
      SQLPAD_ADMIN_PASSWORD: admin
    depends_on:
      - trino

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config/etc:/etc/trino
      - ./trino-config/catalog:/etc/trino/catalog
    depends_on:
      - nessie
      - mongo
      - minio

  dremio:
    image: dremio/dremio-oss
    container_name: dremio
    ports:
      - "9047:9047"
      - 31010:31010
      - 32010:32010
    environment:
      - SERVICES_EXECUTOR_MEMORY=4G
      - SERVICES_COORDINATOR_MEMORY=4G

  nessie:
    image: ghcr.io/projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - QUARKUS_HTTP_PORT=19120
      - NESSIE_VERSION_STORE_TYPE=MONGODB2
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://root:example@mongo:27017/nessie?authSource=admin
      - QUARKUS_MONGODB_DATABASE=nessie
      - nessie.catalog.default-warehouse=warehouse
      - nessie.catalog.warehouses.warehouse.location=s3://warehouse/
      - nessie.catalog.service.s3.default-options.region=us-east-1
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      - nessie.catalog.secrets.access-key.name=admin
      - nessie.catalog.secrets.access-key.secret=admin123

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_DOMAIN: storage
      MINIO_REGION: us-east-1
      MINIO_REGION_NAME: us-east-1
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"

volumes:
  mongo-data:
    driver: local
  trino-config:
    driver: local