services:
  sqlpad:
    image: sqlpad/sqlpad
    container_name: sqlpad
    ports:
      - "3000:3000"
    environment:
      SQLPAD_ADMIN: ${SQLPAD_ADMIN}
      SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
    depends_on:
      - trino

  trino:
    image: trinodb/trino:latest
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino-config/etc:/etc/trino
      - ./trino-config/catalog:/etc/trino/catalog
    depends_on:
      - nessie
      - mongo
      - minio

  dremio:
    image: dremio/dremio-oss
    container_name: dremio
    ports:
      - "9047:9047"
      - 31010:31010
      - 32010:32010
    environment:
      SERVICES_EXECUTOR_MEMORY: ${DREMIO_EXECUTOR_MEMORY}
      SERVICES_COORDINATOR_MEMORY: ${DREMIO_COORDINATOR_MEMORY}

  nessie:
    image: ghcr.io/projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      QUARKUS_HTTP_PORT: ${NESSIE_PORT}
      NESSIE_VERSION_STORE_TYPE: ${NESSIE_VERSION_STORE_TYPE}
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/nessie?authSource=admin
      QUARKUS_MONGODB_DATABASE: ${NESSIE_DATABASE}
      nessie.catalog.default-warehouse: ${NESSIE_DEFAULT_WAREHOUSE}
      nessie.catalog.warehouses.warehouse.location: ${NESSIE_WAREHOUSE_LOCATION}
      nessie.catalog.service.s3.default-options.region: ${NESSIE_S3_REGION}
      nessie.catalog.service.s3.default-options.path-style-access: ${NESSIE_S3_PATH_STYLE_ACCESS}
      nessie.catalog.service.s3.default-options.access-key: ${NESSIE_S3_ACCESS_KEY}
      nessie.catalog.secrets.access-key.name: ${NESSIE_SECRET_NAME}
      nessie.catalog.secrets.access-key.secret: ${NESSIE_SECRET_PASSWORD}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    depends_on:
      - mongo

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_DOMAIN: ${MINIO_DOMAIN}
      MINIO_REGION: ${MINIO_REGION}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

volumes:
  mongo-data:
    driver: local
  trino-config:
    driver: local
  minio-data:
    driver: local